
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/go:1.22
    volumes: 
      - ..:/workspace:cached
    network_mode: "host"
    command: sleep infinity
  
  buildkitd:
    image: moby/buildkit:v0.12.4
    entrypoint: ["buildkitd"]
    command: ["--addr", "tcp://0.0.0.0:8888"]
    privileged: true
    ports:
      - 8888:8888/tcp

  trivy:
    image: aquasec/trivy:0.50.4
    command: ["server", "--listen=0.0.0.0:8887"]
    ports:
      - 8887:8887

  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    
  registry2:
    image: registry:2
    restart: always
    ports:
      - 5001:5000

  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    network_mode: "host"
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://localhost:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
      - NGINX_LISTEN_PORT=8080
    container_name: registry-ui

  registry2-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    network_mode: "host"
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://localhost:5001
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
      - NGINX_LISTEN_PORT=8081
    container_name: registry2-ui
